### ISSUE TITLE
在某些case想不要触发绘制

### ISSUE THREAD

**Issue by zanxiaofei** [LiuHongtao/PaintView#3]
您好，
想在适当的时机关闭绘制，但是之前绘制的内容继续显示
然后再某些case下再恢复绘制，有接口嘛

**Comment by LiuHongtao** [comment]
Hi,

已经更新版本到1.17，增加了`setPaintEnable`接口打开和关闭绘制，请尝试看是否满足需求。

**Comment by zanxiaofei** [comment]
可以满足，十分感谢
